# Site settings
name: Roger Camara
title: Roger Camara | Designer Estratégico - Especialista em UX
description: Designer estratégico especializado em Service Design e User Exprience
url:  http://rogercamara.github.io
baseurl: http://rogercamara.github.io
email: roger.camara@outlook.com
cover: http://rogercamara.github.io/img/og.png
logo: http://rogercamara.github.io/img/emojis/technologist.png
resume: http://rogercamara.github.io/resume.pdf
portfolio: http://rogercamara.github.io/portfolio.pdf
portfolio2: https://www.figma.com/file/skUQ0xQ7JZbBZ3Ly0CTebK/Portfolio-2?node-id=0%3A1
social:
  - title: email
    mailto: roger.camara@outlook.com
  - title: twitter
    url: https://twitter.com/rogercamara
  - title: instagram
    url: https://instagram.com/rogercamara_
  - title: github
    url: https://github.com/rogercamara
  - title: linkedin
    url: https://www.linkedin.com/in/rogercamara

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
